### PR TITLE
first run of LE should work. fix #3

### LINKED ISSUE #3: First run of LE requires accepting TOS from console
```
cert-manager    | {"app":"cert-manager","hostname":"874cd6dd4a07","level":"error","msg":"2017/06/05 20:00:00 Please review the TOS at https://letsencrypt.org/documents/LE-SA-v1.1.1-August-1-2016.pdf","time":"2017-06-05T20:00:00Z"}
cert-manager    | {"app":"cert-manager","hostname":"874cd6dd4a07","level":"error","msg":"2017/06/05 20:00:00 Do you accept the TOS? Y/n","time":"2017-06-05T20:00:00Z"}
cert-manager    | {"app":"cert-manager","hostname":"874cd6dd4a07","level":"error","msg":"2017/06/05 20:00:00 Could not read from console: EOF","time":"2017-06-05T20:00:00Z"}
cert-manager    | {"app":"cert-manager","hostname":"874cd6dd4a07","level":"error","msg":"2017/06/05 20:00:00 Could not complete registration","time":"2017-06-05T20:00:00Z"}
cert-manager    | {"app":"cert-manager","hostname":"874cd6dd4a07","level":"error","msg":"\tacme: Error 500 - urn:acme:error:serverInternal - Error creating new registration","time":"2017-06-05T20:00:00Z"}
```

### PR DESCRIPTION
**Pull request by ahammond**
fixes #3

### CODE REVIEW

File: register_or_renew.go [hunk 1]
```diff
@@ -73,7 +73,7 @@ func RegRenew(logger *log.Entry, filename string, commands chan Cmd, bucket stri
 		var exec Cmd
 		exec.domain = domain
 		exec.promMetric = certificateExecCode
-		command := fmt.Sprintf("%s --email='%s' --domains='%s' --pem --dns='%s' --storage='s3' --path=%s",
+		command := fmt.Sprintf("echo y | %s --email='%s' --domains='%s' --pem --dns='%s' --storage='s3' --path=%s",
```
Comment (onorua) [inline register_or_renew.go]: This can be achieved with `--accept-tos` instead, which is built in into lego:
```
GLOBAL OPTIONS:
   --domains value, -d value   Add domains to the process
   --csr value, -c value       Certificate signing request filename, if an external CSR is to be used
   --server value, -s value    CA hostname (and optionally :port). The server certificate must be trusted in order to avoid further modifications to the client. (default: "https://acme-v01.api.letsencrypt.org/directory")
   --email value, -m value     Email used for registration and recovery contact.
   --accept-tos, -a            By setting this flag to true you indicate that you accept the current Let's Encrypt terms of service.
   --key-type value, -k value  Key type to use for private keys. Supported: rsa2048, rsa4096, rsa8192, ec256, ec384 (default: "rsa2048")
   --path value                Directory to use for storing the data (default: "/Users/onorua/dev/go/src/github.com/onorua/lego/.lego")
   --exclude value, -x value   Explicitly disallow solvers by name from being used. Solvers: "http-01", "tls-sni-01".
   --webroot value             Set the webroot folder to use for HTTP based challenges to write directly in a file in .well-known/acme-challenge
   --memcached-host value      Set the memcached host(s) to use for HTTP based challenges. Challenges will be written to all specified hosts.
   --http value                Set the port and interface to use for HTTP based challenges to listen on. Supported: interface:port or :port
   --tls value                 Set the port and interface to use for TLS based challenges to listen on. Supported: interface:port or :port
   --dns value                 Solve a DNS challenge using the specified provider. Disables all other challenges. Run 'lego dnshelp' for help on usage.
   --http-timeout value        Set the HTTP timeout value to a specific value in seconds. The default is 10 seconds. (default: 0)
   --dns-timeout value         Set the DNS timeout value to a specific value in seconds. The default is 10 seconds. (default: 0)
   --dns-resolvers value       Set the resolvers to use for performing recursive DNS queries. Supported: host:port. The default is to use Google's DNS resolvers.
   --pem                       Generate a .pem file by concatanating the .key and .crt files together.
   --help, -h                  show help
   --version, -v               print the version
```
